
  # Replace the text below to customize your site
site_name: Clase de Proyectos 1
site_description: Clase de Proyectos 1 UIA Puebla
site_author: aristarco
copyright: Copyright 2024 Aristarco Cortés - Creactive Commons Attribution Non-commercial

site_url: https://aristarco.github.io/Pry1_Clase/
repo_url: https://github.com/aristarco/Pry1_Clase

repo_name: Clase_proyectos_1/2025/aristarco-cortes

extra:
  social:
    # Change to your own social media or remove line to hide. 
    # For more social icons ideas at https://squidfunk.github.io/mkdocs-material/setup/setting-up-the-footer/#social-links
    - icon: fontawesome/brands/instagram
      link: https://instagram.com/aristarco_dixit
    - icon: fontawesome/brands/facebook
      link: https://facebook.com/aristarco.cortes
    - icon: fontawesome/brands/linkedin
      link: h-cortes/linkedin.com/aristarco-cortes

theme:
  # The name of the theme, needs to match your requirements.txt file
  name: material
  nav:
  - Inicio: index.md
  # Material theme options:
  palette:
    # try other colors from https://squidfunk.github.io/mkdocs-material/setup/changing-the-colors/
    primary: teal
    accent: deep purple
  font:
    # See available fonts from https://fonts.google.com/
    text: Montserrat
    code: Roboto Mono
  #icon:
    # Read about icons at https://squidfunk.github.io/mkdocs-material/setup/changing-the-logo-and-icons/
    # logo: icons/Aristarjos.png
  logo: ./images/home/Aristarjos_ico.png
    #logo: material/library
    #repo: material/gitlab
  features:
    - navigation.tabs
    - navigation.footer
#  favicon: ./images/home/Aristarjos_ico.png
# Read more here https://squidfunk.github.io/mkdocs-material/customization/#additional-css 
# extra_css:
#   - stylesheets/extra.css

# extra_javascript:
#   - 'javascript/extra.js'


# See more extensions at https://squidfunk.github.io/mkdocs-material/reference/
markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
  - toc:
      permalink: true
  # https://squidfunk.github.io/mkdocs-material/reference/admonitions/
  - pymdownx.details
  # https://squidfunk.github.io/mkdocs-material/reference/content-tabs/
  - pymdownx.tabbed:
      alternate_style: true 
  - pymdownx.superfences
  - tables
  - footnotes
  - attr_list
  - md_in_html
